#!/bin/sh
# @(#)ldapclient
#
# Copyright (c) 2001 PADL Software Pty Ltd. All rights reserved.
# See COPYING for license terms.
#
DEFAULTDOMAINNAME=`/bin/domainname`

if [ "X$FORCE_LDAPCLIENT" = "X" -a -f /etc/ldap.conf ]; then
	echo "/etc/ldap.conf already exists."
	echo "Please move out of the way and rerun ldapclient."
	exit 1
fi

question="Enter your NIS domain [$DEFAULTDOMAINNAME]:"
echo "$question " | tr -d '\012' > /dev/tty
read DOMAINNAME
if [ "X$DOMAINNAME" = "X" ]; then
	if [ "X$DEFAULTDOMAINNAME" = "X" ]; then
		question="Enter your X.500 search base:"
		echo "$question " | tr -d '\012' > /dev/tty
		read LDAP_BASEDN
		if [ "X$LDAP_BASEDN" = "X" ]; then
			echo "You must specify a search base."
			exit 2
		fi
	else
		DOMAINNAME=$DEFAULTDOMAINNAME
	fi
fi

question="Enter the name of your LDAP server [ldap]:"
echo "$question " | tr -d '\012' > /dev/tty
read LDAPHOST
if [ "X$LDAPHOST" = "X" ]; then
	LDAPHOST="ldap"
fi

question="Enter your profile name:"
echo "$question " | tr -d '\012' > /dev/tty
read PROFILE

if [ "X$LDAP_BASEDN" != "X" ]; then
	if [ "X$PROFILE" != "X" ]; then
		ldapprofile -h "$LDAPHOST" -b "$LDAP_BASEDN" -p "$PROFILE" > /etc/ldap.conf
	else
		ldapprofile -h "$LDAPHOST" -b "$LDAP_BASEDN" > /etc/ldap.conf
	fi
else
	if [ "X$PROFILE" != "X" ]; then
		ldapprofile -h "$LDAPHOST" -d "$DOMAINNAME" -p "$PROFILE" > /etc/ldap.conf
	else
		ldapprofile -h "$LDAPHOST" -d "$DOMAINNAME" > /etc/ldap.conf
	fi
fi

if [ $? -ne 0 ]; then
	echo "$0: ldapprofile returned non-zero exit status"
	e=$?
else
	echo "$0: ldapprofile created /etc/ldap.conf"
	e=$?
fi

exit $e

